### ISSUE TITLE
Errors in fits

### ISSUE THREAD

**Issue by k-ortner** [jsmallcombe/jRootAnalysisTools#1]
This isn't necessarily an issue but might a misunderstanding on how the errors are propagated. 

When I fit from the fit panel using a 0th order background the errors are roughly the square root of the area which makes sense to me. However, when I use a higher order background or the step function, the errors seem really high. In some cases 50-100 times the error that I have obtained using TPeakFitter or other fitting means in the past which also included various background fits. 

can you direct me to how these errors are created so I can investigate?

**Comment by jsmallcombe** [comment]
Depending on the fit, there may be insufficient data to constrain the additional parameters.
Ideally using a more complex function should improve the fit, decrease the chi-squared, and give you all together better uncertainties.
However if you don't have enough background bins, any additional background parameters will be poorly constrained, and through correlations actually increase the uncertainty in the peak parameters. The step parameter in particular can be hard to constrain.

100 times larger is a bit much.

The peak area and errors are calculated from the fit results in the class function Ultrapeak::MakeData() in src/j_ultrapeak.cpp which is called by the fitting routine. This takes a TF1 using the class UltrapeakArea, defined in include/j_ultrapeak.h, which, when given the parameter list from the original fit function, returns the area of the peak(s). The error of this function is calculated analytically from the covariance matrix of the parameters from the fit using the standard error formula:
![ErrooFn](https://user-images.githubusercontent.com/15150313/117424614-de16a000-af19-11eb-8f13-36f6854c88c4.png)

The application of this error formula is implemented in the library function AnalyticalFullCovError() defined in src/j_utility.cpp 
The "integral" area and error do not depend directly on the peak parameters, but still depend on the background parameters. So if these are uncertain due to poorly constrained correlations with the peak parameter you will see the same problem.

If you find any mistakes please either let me know or make a pull request with the correction.

I suspect the problem is poorly constrained parameter correlations, I'd be happy to advise on particular fits if you want to upload a screenshot.

**Comment by k-ortner** [comment]
It is likely the constraints. I am working on a spectrum with many peaks and multi-peak fitting is the only way to go. I suspect with TPeakFitter, there are more constraints I was using leading to lower errors. I'll keep this open for now (unless you'd prefer not to) and actually go through fitting my spectrum to see how it compares and report back.

Just to also clarify, I am using "The Shadow" release and not the master branch which has "james_.." naming convention and not "j_..". Is this still the release you recommend? I did try the master briefly and felt the fitting was giving more errors.

Anyway, it is an awesome tool you have created and will make my life fitting over 300 transitions much easier!

**Comment by jsmallcombe** [comment]
I'm not sure how TPeakFitter handles constraints for the more tricky shapes. But in Ultrapeak the tail and steps can be particularly tricky with degenerate peaks. Unless you have data with large peaks steps, or very isolated peaks, the stepped backgrounds are probably best avoided.

I would suggest the newer release Samuel Johnson, which I have now taken out of pre-release. I made some fairly big changes to the fitting logic and output, so I'm not surprised you saw more errors. Users will see more "errors" in terminal, but most of these minimizer issues were always present in the fit they just weren't as well publicised. That said, the core functions in the previous versions are still correct so if you are getting better results, and are happier, with The Shadow those results should be valid.
Though I think the logic for the "Integral" area isn't great in that version.

I'm pleased some other people are getting use out the tool. And I'm happy to leave this issue open if you're going to report back later.
