### ISSUE TITLE
Fit Centroid Uncertainty 

### ISSUE THREAD

**Issue by nastaran-s** [jsmallcombe/jRootAnalysisTools#2]
Hello, 
I need to record the uncertainties of my centriod values after fitting. I see a sigma value of the peak is given. I assume that is FWHM/2.35 (please confirm if it is right). In front of centroid values, I see the errors are given. Are those errors the centroid uncertainties? these error values look a bit smaller that what I expect.  
I would appreciate any comments on this issue. 
![jRoot](https://user-images.githubusercontent.com/57689210/151605572-58ca2080-9028-48f9-98a1-99de17743c54.png)

**Comment by jsmallcombe** [comment]
Sigma here is a fit parameter, which can only be related directly to FWHM by that relation when dealing with a pure Gaussian.
Your sharing parameter is close to 1, so its still approximately true.
(I haven't done the maths to work out the complete relation for FWHM as I'm not generally interested in it.)

The errors you should take are from the table at the bottom, not the fit status.
Here a centroid error of 0.016 may seem small, but for a peak with 60000 counts the centroid is very well defined, so this does not looks surprising to me.

I always like to remind people, fit results only give you the STATISTICAL uncertainty. While the chi-squared gives a measure of how well your function matches the data, there is a SYSTEMATIC uncertainty introduced when one says "This function describes the peak". For instance here, we have a very small statistical uncertainty for the peak fit parameter corresponding to the centroid of the Gaussian component, but the centroid is not the same as the spectroscopic peak maximum due the decay component. If we instead fit with a Gaussian alone we would get a different centroid, again with a small STATISTICAL uncertainty.

You could take the difference between X_max. and Cent. as a measure of the SYSTEMATIC uncertainty.

And of course these is an uncertainty due to calibration not represented here.

Also, it looks like you're background fit isn't great.
